### ISSUE TITLE
Can't press play

### ISSUE THREAD

**Issue by SaberShock** [ParadoxGameConverters/paradoxGameConverters#522]
So, this is likely just user error, but I'm new to this whole thing. My apologies if you've addressed this before, but I couldn't find anything. Heck. I'm not even sure if this was the right place to bring this up. I'm really sorry. Anyway, the problem I'm having is 2 fold. So first, I can't convert any save that wasn't autosaved at the end date. It pops up with a message about renaming the file. Second, and this is the most troubling to be honest, if I do get the files to convert, it doesn't actually let me play them in Vic2. It loads fine. It gets to the choose your nation map just fine. The map clearly shows the world as I saved it in EU4. However, the play button on the bottom left stays gray no matter how many times I click. Any idea what I'm doing wrong here?

**Comment by IohannesIohannium** [comment]
First problem may be tied with the language the save is named (unless it's Windows-1252 safe Latin, the converter will be not good working).

Second problem, addressed in #507, has the solution of inverting the bookmarks orders in the `common/bookmarks.txt` file generated in the Vic2 mod.

**Comment by Idhrendur** [comment]
@IohannesIohannium Wait, compressed saves with non-Latin characters have problems being converted? By any chance, can you create a save of this kind? (I don't think I'm able to on my computer)

**Comment by SaberShock** [comment]
@IohannesIohannium So, the problem then that the file is compressed. I tried saving the game with the compression option unselected. The save converted fine. So, that solves that on my end and it seems you guys know about it on yours.

As for the second, I see this had been addressed. My apologies. That's a really weird thing to have caused this. I'm assuming it has something to do with the game not understanding why 1836 is coming before 1821 since the date usually goes earliest to latest, but I don't know. It's working now. Thank you for your time.

**Comment by IohannesIohannium** [comment]
@Idhrendur It may happen, I guess, but I can't generate such files neither, as Notepad++ forbids me inserting, e.g., Cyrillic in savefiles due to codification.

**Comment by kratostatic** [comment]
Yeah the 1836-1821 one is mostly my fault.  Iohannes put in an 1821 start date with the idea that we'll flesh it out a bit as time went by.  I thought that if it's the first option people will think its the default and then wonder why they can't research anything or don't have Liberal parties so I switched them about.  Now to be fair when I tested this before release it didn't have this issue!

On the save name thing couldn't we just use Altcodes when naming the save?

**Comment by kratostatic** [comment]
Quick bit of research later - Cyrillic characters can't be 8859-15 as the standard doesn't support Cyrillic characters (it's a "Western Europe" code set).  It could in theory be UTF-8 or UCS-2.

Now unfortunately, they also can't be accessed with Alt-codes on my english-language keyboard which was a bit of a surprise to me!  I don't know if there are any Alt-code accessible symbols which are not Windows-1252 supported symbols, but there are some alt-code accessable symbols which are not in the Windows-1252 code set, for example ♣ which is Alt-5.  This is also not in 8859-15.
