### ISSUE TITLE
Text transformation problems in name files

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/paradoxGameConverters#608]
"Adding to the madness, here it is how "š" is somehow both supported and unsupported by the latest release.

![image](https://user-images.githubusercontent.com/24550392/40921007-8c120182-680e-11e8-8890-82f1feaedec6.png)

EDIT:
By seeing the names' file, I could conclude that "š" became [SCI], "Š" became [VTS], "ž" became [PM], "Ž" became [SS2] (not pictured), "â" is back to normal (not pictured).
![image](https://user-images.githubusercontent.com/24550392/40931647-136df8c6-682c-11e8-88fb-c51c58937923.png)"

**Comment by Idhrendur** [comment]
@thatsgerman, I know it's been a while, but do you remember which save you used to find this? I'm not able to see similar things in the names file with my usual test save.

**Comment by IohannesIohannium** [comment]
Probably been solved, but I used the EU4Vic2 culture file (vanilla Vic2 has
no š there). You can check it, though, by seeing how the province Niš
(Serbia) or Požega (Slovakia) are handled in a debug conversion.

**Comment by Idhrendur** [comment]
Okay, it definitely looks like using Windows 1252 is the trick, and doing so even eliminates the need for replacing bad characters. Time to code it up properly.
