### ISSUE TITLE
Crash upon army conversion

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/paradoxGameConverters#658]
The Vic2HoI4 release 0.2H crashes on "Converting armies"

Savefiles used for test:
- standard 1914 historical start
- EU4Vic2 conversion with countries with modern borders

**Comment by IohannesIohannium** [comment]
Here they are, whereas 1914save.v2 is the first, and the input ones are save and mod of the second try.
[saves.zip](https://github.com/ParadoxGameConverters/paradoxGameConverters/files/2410807/saves.zip)

**Comment by Idhrendur** [comment]
Look like this was fixed by previous changes.
