### ISSUE TITLE
Ideologies

### ISSUE THREAD

**Issue by kstar234** [ParadoxGameConverters/paradoxGameConverters#678]
Is it possible to directly carry over the vic2 ideologies?

**Comment by IohannesIohannium** [comment]
Depends by what do you mean with "Vic2 ideologies".

Currently, the HoI4 converter gives you three options:
- "Keep default", Vanilla HoI4 four ideology groups
- "Keep all", six HoI4 ideology groups (adding to Vanilla "absolutist" and "radical (read, anarcho-liberal)")
- "Keep major", which works as the one above, but eliminating the groups that were not ruling in your save

**Comment by kstar234** [comment]
Well what I mean is all the vic2 ideologies Communism,Socialism,Liberalism etc. as opposed to lumping those into democratic

**Comment by IohannesIohannium** [comment]
With some modding, it could be done. If You wish, I could mod it for You.

**Comment by Idhrendur** [comment]
Or if you want to do it yourself, you would need to edit governmentMapping.txt in the Vic2ToHoI4 folder, then modify blankMod for any new ideologies you added, plus any of the other text files in the Vic2ToHoI4 folder dealing with ideologies.
