### ISSUE TITLE
More flag problems

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/paradoxGameConverters#684]
The smallest flags in my personal megacampaign exhibit some problems. Israel, Oman, Scotland, and Catalonia all seem unusually dark. It may be an alpha channel issue.

**Comment by IohannesIohannium** [comment]
This bug is present in flags of all sizes, making some colours transparent:
![image](https://user-images.githubusercontent.com/24550392/48421843-96a26500-e75d-11e8-8ec8-6d1a94ffd01d.png)

**Comment by Idhrendur** [comment]
And it's an easy fix, so done.
