### ISSUE TITLE
Where are the exe files?

### ISSUE THREAD

**Issue by tannerflick4** [ParadoxGameConverters/paradoxGameConverters#704]
For the Vicky 2 to Hoi3 converter, where is the .exe file for it?

**Comment by IohannesIohannium** [comment]
The page for Vic2HoI3 converter files is this: https://github.com/ParadoxGameConverters/Vic2ToHoI3/releases

**Comment by Idhrendur** [comment]
Additionally, the last official release is here: https://github.com/ParadoxGameConverters/paradoxGameConverters/releases/tag/Vic2ToHoI3-1.2

**Comment by tannerflick4** [comment]
I know where the files and download are, but I’m wondering where is the exe
in the files? I cannot figure out how to run the converter if I can’t find
the exe.

**Comment by Idhrendur** [comment]
The one I linked has the executable in the download (make sure to grab the converter, not the test results). The other link is not ready yet.

**Comment by tannerflick4** [comment]
Thank you! I see it now.

**Comment by Idhrendur** [comment]
You're welcome!

**Comment by tannerflick4** [comment]
How would I fix a crash with the converted save from vicky 2 to hoi3? I can do a few clicks in game but then it crashes for me. I have the game patched for more memory too.

**Comment by Idhrendur** [comment]
Sadly, I'm not sure about that. Try and check for error messages in the game logs, or the converter logs. Look around and see if anything is obviously broken.

**Comment by tannerflick4** [comment]
Alright, fixed the crash! Went though from '36-'48 though, and no war broke out. My county's diplo AI declared a war on a landlocked state in India, but we never fought lol. Why is there no war, or did I just get unlucky?
